#!/usr/bin/env python3
"""Generates Perspective themes from the Nautilus HMI's design tokens.

Perspective themes are config resources — a folder of CSS under
`config/resources/core/com.inductiveautomation.perspective/themes/<name>/` — so a theme is a data artefact,
not code. That is why this is a generator and not a module: the module only has to deliver the output.

The approach is to IMPORT Perspective's own base theme and override, rather than restate it. Its light and
dark bases define 118 variables; Nautilus has opinions about perhaps twenty-five of them. Overriding that
subset keeps every Perspective component working (they reference variables we never think about) while the
colours that carry meaning become Nautilus's. `dark-cool` is built exactly this way and is the model here.

  tools/generate-perspective-theme.py <hmi/src/lib/theme.css> <output-dir>
"""
import re
import sys
from pathlib import Path

# Nautilus token -> the Perspective variables it should drive.
#
# Perspective's names are structural ("the nested container's background"); Nautilus's are semantic ("the
# surface a card sits on"). This table is where that translation is decided, and it is the whole design
# content of the theme pack — everything else is plumbing.
MAPPING = {
    # ── ground, surfaces, edges ──
    "bg":            ["containerRoot"],
    "surface":       ["container", "input", "contextBackground"],
    "surface-2":     ["containerNested"],
    "border":        ["border", "containerBorder"],
    "ink":           ["label", "icon"],
    "muted":         ["label--disabled", "icon--disabled", "border--disabled", "input--disabled"],

    # ── the one brand colour, and its states ──
    "accent":        ["callToAction", "callToActionHighlight", "icon--selected"],
    "primary-hover": ["callToAction--hover"],
    "primary-bg":    ["callToAction--active", "callToAction--activeAlt"],

    # ── status. In Nautilus these are RESERVED for process state; Perspective uses the same four for
    #    feedback, which is a near-enough match that sharing them is right rather than lazy.
    "crit":          ["error", "symbolFill--faulted", "symbolStroke--faulted"],
    "warn":          ["warning", "warningSecondary"],
    "good":          ["success", "symbolFill--running", "symbolStroke--running", "indicator"],
    "s1":            ["info", "infoSecondary"],

    # ── P&ID symbols and pipework. Perspective ships its own tank/pump/valve symbols; these make them obey
    #    the same process-state palette as the Nautilus ones, so a screen mixing both is not two languages.
    "muted:stopped": ["symbolFill--stopped", "symbolStroke--stopped", "indicatorOff"],
    "surface-2:sym": ["symbolFill--default", "pipePrimaryFill"],
    "axis":          ["symbolStroke--default", "pipeStroke", "pipeSecondaryFill"],
    "accent:pipe":   ["pipeSelectStroke"],
}

# Nautilus has no 10–100 neutral ramp, and inventing one by hand would be ten arbitrary hex values that
# drift from the palette the moment it changes. Derived from the two ends instead, so it stays in the family.
NEUTRAL_STEPS = 10


def read_tokens(css: str, selector: str) -> dict[str, str]:
    """The custom properties declared in the first block matching `selector`."""
    start = css.find(selector)
    if start < 0:
        raise SystemExit(f"no {selector} block in the theme")
    block = css[css.index("{", start) + 1:css.index("}", start)]
    return {m.group(1): m.group(2).strip()
            for m in re.finditer(r"--([a-zA-Z0-9-]+)\s*:\s*([^;]+);", block)}


def neutrals(dark: bool) -> list[str]:
    """A neutral ramp mixed between the theme's ground and its ink.

    Perspective numbers neutrals 10 (darkest) to 100 (lightest) regardless of theme, and its dark themes
    simply invert which end is which. Mixing keeps the ramp tied to whatever --bg and --ink become.
    """
    out = []
    for i in range(NEUTRAL_STEPS):
        pct = round(i * 100 / (NEUTRAL_STEPS - 1))
        a, b = ("bg", "ink") if dark else ("ink", "bg")
        out.append(f"color-mix(in srgb, var(--n-{a}) {100 - pct}%, var(--n-{b}) {pct}%)")
    return out


def build(tokens: dict[str, str], dark: bool) -> str:
    lines = [
        "/* Generated by tools/generate-perspective-theme.py from the Nautilus HMI's tokens.",
        " * Do not edit: change hmi/src/lib/theme.css and regenerate.",
        " *",
        " * Perspective's own base is imported first, so every variable this file does not mention keeps",
        " * working. Only the ones Nautilus has an opinion about are overridden.",
        " */",
        f'@import "../{"dark" if dark else "light"}/variables.css";',
        "",
        ":root {",
        "    /* the Nautilus tokens themselves, so the mapping below reads as the mapping it is */",
    ]
    for name, value in sorted(tokens.items()):
        lines.append(f"    --n-{name}: {value};")

    lines += ["", "    /* neutral ramp, mixed from this theme's ground and ink */"]
    for i, value in enumerate(neutrals(dark)):
        lines.append(f"    --neutral-{(i + 1) * 10}: {value};")

    lines += ["", "    /* Nautilus tokens mapped onto the names Perspective's components actually read */"]
    for source, targets in MAPPING.items():
        token = source.split(":")[0]
        if token not in tokens:
            print(f"  warning: no --{token} in the theme; skipping {targets}", file=sys.stderr)
            continue
        for target in targets:
            lines.append(f"    --{target}: var(--n-{token});")

    lines += ["", "    /* shape and type */",
              "    --borderRadius: var(--n-radius, 4px);",
              "    --borderRadiusInput: var(--n-radius, 4px);",
              "}", ""]
    return "\n".join(lines)


def write_theme(out: Path, name: str, dark: bool, tokens: dict[str, str]) -> None:
    d = out / name
    d.mkdir(parents=True, exist_ok=True)
    base = "dark" if dark else "light"

    (d / "variables.css").write_text(build(tokens, dark))
    # Mirrors the built-in dark-cool: our variables first, then Perspective's own layers on top.
    (d / "index.css").write_text(
        '@import "./variables.css";\n'
        '@import "../light/fonts.css";\n'
        f'@import "../{base}/globals.css";\n'
        '@import "../light/app/index.css";\n'
        '@import "../light/common/index.css";\n'
        '@import "../light/designer/index.css";\n'
        '@import "../light/palette/index.css";\n'
        + (f'@import "../{base}/palette/index.css";\n' if dark else "")
    )
    (d / "config.json").write_text('{\n  "entrypoint": "index.css",\n  "isPrivate": false\n}\n')
    (d / "resource.json").write_text(
        '{\n'
        '  "scope": "G",\n'
        f'  "description": "Nautilus {"dark" if dark else "light"} theme for Perspective.",\n'
        '  "version": 1,\n'
        '  "restricted": false,\n'
        '  "overridable": true,\n'
        '  "files": [\n    "config.json",\n    "index.css",\n    "variables.css"\n  ],\n'
        '  "attributes": {}\n'
        '}\n'
    )
    print(f"  {name}: {len((d / 'variables.css').read_text().splitlines())} lines")


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    css = Path(sys.argv[1]).read_text()
    out = Path(sys.argv[2])

    dark = read_tokens(css, ":root[data-theme='dark']")
    light = read_tokens(css, ":root[data-theme='light']")
    shared = read_tokens(css, ":root {")
    print(f"read {len(dark)} dark, {len(light)} light, {len(shared)} shared tokens")

    write_theme(out, "nautilus-dark", True, {**shared, **dark})
    write_theme(out, "nautilus-light", False, {**shared, **light})


if __name__ == "__main__":
    main()
